// Generated by CoffeeScript 1.10.0
var hasProp = {}.hasOwnProperty;

Array.prototype.includes = function(needle) {
  var NaNcheck, i, item, len, len1;
  len = this.length;
  if (len === 0) {
    return false;
  }
  NaNcheck = function(x) {
    return x !== x;
  };
  for (i = 0, len1 = this.length; i < len1; i++) {
    item = this[i];
    if ((item === needle) || ((NaNcheck(item)) && (NaNcheck(needle)))) {
      return true;
    }
  }
  return false;
};

Object.prototype.map = function(callback) {
  var k, results, v;
  results = [];
  for (k in this) {
    if (!hasProp.call(this, k)) continue;
    v = this[k];
    results.push(callback(k, v));
  }
  return results;
};

Array.prototype.remove = function(item) {
  var index;
  index = this.indexOf(item);
  if (index >= 0) {
    return this.splice(index, 1);
  }
};
